DriveHub/DriveHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace="account")),
    path('ai/', include('ai.urls', namespace="ai")),
    path('', include('advert.urls', namespace="advert")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

DriveHub/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('my-ads/', views.my_ads, name='my-ads'),
    path('favourites/', views.favourites, name='favourites'),
    path('settings/', views.settings, name='settings'),
    path('logout/', views.logout, name='logout'),
]

DriveHub/advert/urls.py
from django.urls import path
from . import views

app_name = 'advert'

urlpatterns = [
    path('', views.home, name='home'),
    path('ajax/get-models/', views.get_models_by_brand, name='get-models-by-brand'),
    path('ajax/get-cities/', views.get_cities_by_region, name='get-cities-by-region'),
    path('ajax/toggle-favourite/', views.toggle_favourite, name='toggle-favourite'),
    path('create/', views.create_advert, name='create-advert'),
    path('delete/<int:advert_id>/', views.delete_advert, name='delete-advert'),
    path('advanced-filters/', views.advanced_filters, name='advanced-filters'),
    path('<slug:slug>/', views.advert_detail, name='advert-detail'),
]

DriveHub/ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'

urlpatterns = [
    path('chat/', views.chat, name='chat'),
]

DriveHub/templates/footer.html
{% load static %}

<footer>
    <div class="footer-container">
        <div class="footer-row-1">
            <div class="footer-col-1">
                <a class ="footer-logo" href="{% url 'advert:home' %}">
                    <img class="footer-logo-img" src = "{% static 'icons/logo.svg' %}">
                </a>
                <p class="footer-about">
                    DriveHub — це зручна платформа для автовласників, яка допомагає легко продавати та купувати за своїм авто.
                </p>
            </div>
            <div class="footer-col-2">
                <div class="nav-col">
                    <span>Сервіси</span>
                    <a href="#">Продажа авто</a>
                    <a href="#">Для бізнесу</a>
                </div>
                <div class="nav-col">
                    <span>Про компанію</span>
                    <a href="#">Вакансії</a>
                </div>
                <div class="nav-col">
                    <span>Тех. підтримка</span>
                    <a href="#">Допомога по сайту</a>
                    <a href="#">help@drivehub.com.ua</a>
                    <a href="#">Telegram @drivehub_ua</a>
                </div>
            </div>
        </div>
        <div class="footer-row-2">
            <p class="footer-copy">
                2025 drivehub.com.ua
            </p>
            <div class="footer-rights">
                <a href="#">
                    Користувацька угода
                </a>
                <a href="#">
                    Політика приватності
                </a>
            </div>
        </div>
    </div>
</footer>

DriveHub/templates/header.html
{% load static %}

<header>
    <div class="header-container">
        <div class="header-row">
            <div class="col-1">
                <a class ="header-logo" href="{% url 'advert:home' %}">
                    <img class="header-logo-img" src = "{% static 'icons/logo.svg' %}">
                </a>
            </div>
            <form class="col-2" action="{% url "advert:advanced-filters" %}" method="post">
                {% csrf_token %}
                <nav class="header-nav">
                    <ul class="header-menu">
                        <li class = "menu-item">
                            <button class = "header-menu-link" type="submit" name="car_type" value="new">Нове авто</button>
                        </li>
                        <li class = "menu-item">
                            <button class = "header-menu-link" type="submit" name="car_type" value="used">Вживане авто</button>
                        </li>
                        <li class = "menu-item">
                            <a class = "header-menu-link" href="{% url "advert:create-advert" %}">Продати авто</a>
                        </li>
                        <li class = "menu-item l">
                            <div class="login-btn">
                                {% if user.is_authenticated %}
                                <a class="header-profile-logo" href="{% url 'account:my-ads' %}">
                                    <div>{{ user.first_name|slice:":1"|upper }}</div>
                                </a>
                                {% else %}
                                <a class="login" href="{% url 'account:login' %}">
                                    <div class="login-img-container">
                                        <img src="{% static 'icons/login.svg' %}">
                                    </div>
                                    <span class="login-title">Увійти</span>
                                </a>
                                {% endif %}
                            </div>
                            <div class="menu">
                                <a class="menu-adverts" href="{% url 'account:my-ads' %}">
                                    <img class="black-icon" src="{% static 'icons/my-ads-icon-black.svg' %}" alt="">
                                    <img class="blue-icon" src="{% static 'icons/my-ads-icon-blue.svg' %}" alt="">
                                    <span>Мої оголошення</span>
                                </a>
                                <a class="menu-favourite" href="{% url 'account:favourites' %}">
                                    <img class="black-icon" src="{% static 'icons/favorite-icon-black.svg' %}" alt="">
                                    <img class="blue-icon" src="{% static 'icons/favorite-icon-blue.svg' %}" alt="">
                                    <span>Обране</span>
                                </a>
                                <a class="menu-settings" href="{% url 'account:settings' %}">
                                    <img class="black-icon" src="{% static 'icons/setting-icon-black.svg' %}" alt="">
                                    <img class="blue-icon" src="{% static 'icons/setting-icon-blue.svg' %}" alt="">
                                    <span>Налаштування</span>
                                </a>
                                <a class="menu-logout" href="{% url "account:logout" %}">
                                    <img class="black-icon" src="{% static 'icons/logout-icon-black.svg' %}" alt="">
                                    <img class="blue-icon" src="{% static 'icons/logout-icon-blue.svg' %}" alt="">
                                    <span>Вийти</span>
                                </a>
                            </div>
                        </li>
                        <li class = "menu-item c">
                            <div class = "create-btn">
                                <a class="create" href="{% url "advert:create-advert" %}">
                                    <div class="create-img-container">
                                        <img src="{% static 'icons/plus.svg' %}">
                                    </div>
                                    <span class="create-title">Розмістити</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </form
        </div>
    </div>
</header>